name: TezosKit
options:
  bundleIdPrefix: com.keefertaylor
settings:
  LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks @loader_path/../Frameworks $(PROJECT_DIR)/Carthage/Build/iOS"
targets:
  TezosKit_iOS:
    type: framework
    platform: iOS
    sources: [TezosKit, Extensions]
    deploymentTarget: 10.0
    scheme:
      testTargets:
        - TezosKitTests_iOS
      gatherCoverageData: true
    postCompileScripts:
      - script: swiftlint autocorrect --config .swiftlint.yml
        name: SwiftLint
    settings:
      base:
        PRODUCT_NAME: TezosKit
    dependencies:
      - carthage: BigInt
      - carthage: DTTJailbreakDetection
      - carthage: Sodium
      - carthage: CryptoSwift
      - carthage: PromiseKit
      - carthage: Base58Swift
      - carthage: MnemonicKit
      - carthage: secp256k1
  TezosKit_macOS:
    type: framework
    platform: macOS
    sources: [TezosKit, Extensions]
    scheme:
      testTargets:
        - TezosKitTests_macOS
      gatherCoverageData: true
    postCompileScripts:
      - script: swiftlint autocorrect --config .swiftlint.yml
        name: SwiftLint
    settings:
      base:
        PRODUCT_NAME: TezosKit
    dependencies:
      - carthage: BigInt
      - carthage: Sodium
      - carthage: CryptoSwift
      - carthage: PromiseKit
      - carthage: Base58Swift
      - carthage: MnemonicKit
      - carthage: secp256k1
  TezosKitTests:
    type: bundle.unit-test
    platform: [iOS, macOS]
    sources: [Tests/UnitTests, Tests/Common]
    dependencies:
      - target: TezosKit_${platform}
  TezosKitIntegrationTests:
    type: bundle.unit-test
    platform: [iOS, macOS]
    sources: [Tests/IntegrationTests, Tests/Common]
    dependencies:
      - target: TezosKit_${platform}
  SecureEnclaveExample:
    type: application
    platform: iOS
    deploymentTarget: "10.0"
    sources: [Examples/SecureEnclave]
    dependencies:
      - target: TezosKit_iOS
